package SourceParser.Tokenizer;

public enum TokenType {
    PACKAGE, IMPORT,

    PUBLIC, PRIVATE, PROTECTED,

    STATIC, FINAL, ABSTRACT,

    CLASS, INTERFACE, ENUM, EXTENDS, IMPLEMENTS,

    INT, LONG, FLOAT, DOUBLE, CHAR, BOOLEAN, VOID, STRING,

    IF, ELSE, FOR, WHILE, DO, RETURN,

    TRY, CATCH, FINALLY, THROW, THROWS,

    LPAREN, RPAREN, LBRACE, RBRACE, LBRACKET, RBRACKET, LT, GT, COMMA, SEMICOLON, DOT, COLON,

    ASSIGN, PLUS, MINUS, STAR, SLASH, PERCENT,

    WHITESPACE, NEWLINE, COMMENT,

    EOF, UNKNOWN
}